### PR TITLE
Task/fix write device memory

### PR DESCRIPTION
**Pull request by i-n-g-o**
get tlv.size() before calling std::move(tlv), otherwise sentSize is always 0 (memory address would not advance)

### CODE REVIEW

**Comment by christophe-calmejane** [comment]
Now **that** would explain why the first chunk is always sent twice!
Not that critical as it only impacts the first chunk, but indeed the first one is considered _lost_ and resent by _onUserWriteDeviceMemoryResult_ (which correctly handles the moved TLV).
Actually, it would be good if you could add the exact same comment that I've put in **onUserWriteDeviceMemoryResult**, explaining why a copy of the value is taken.
Thanks!

**Comment by i-n-g-o** [comment]
It was more serious in our case: firmware rejected the same chunk returning an error therefore uploading data was canceled.

I added the comment. (And moved the other comment one line up for readablity)

**Comment by christophe-calmejane** [comment]
Thanks, I'll merge this today.

On a side note, if strictly following the entity state machine, your firmware is not supposed to reject the chunk as the only condition in the state machine for a chunk to be rejected is if it's outside the buffer range (although a controller stricly following it's own state machine wouldn't be allowed to send twice the same chunk :) )

**Comment by i-n-g-o** [comment]
thanks! :)

**Comment by christophe-calmejane** [comment]
Merged, thanks!

**Pull request closed without merging**
