### PR TITLE
Fix blanking ncurses window on getch in examples

### PR DESCRIPTION
**Pull request by romansavrulin**
fix in a single PR, as you asked. Files are linted, so you can merge

refs:
https://stackoverflow.com/questions/19748685/curses-library-why-does-getch-clear-my-screen

### CODE REVIEW

**Comment by romansavrulin** [comment]
@christophe-calmejane I prefer to use function over the macro, besides, you already have this style for other windowing procedures. I will rename `_getch` to `get_user_choice` and update a PR

**Comment by christophe-calmejane** [comment]
> @christophe-calmejane I prefer to use function over the macro, besides, you already have this style for other windowing procedures. I will rename `_getch` to `get_user_choice` and update a PR

That would be fine thanks. I don't care that much about coding style in samples anyway :)

**Comment by romansavrulin** [comment]
had to add  `#!/usr/bin/env bash` to this commit, in order to be able to use bash 5.0 on Mac

**Comment by christophe-calmejane** [comment]
> had to add `#!/usr/bin/env bash` to this commit, in order to be able to use bash 5.0 on Mac

Sure that's not a problem.
I already grep+sed all my bash scripts on my disk (all projects) to update :)

Regardless, `bash ./fix_files.sh` should have worked.

**Comment by romansavrulin** [comment]
@christophe-calmejane I'm Just curious: what's your merge policy? I saw you haven't merged any PR on this repo using GitHub provided tools. Why that?

**Comment by christophe-calmejane** [comment]
> @christophe-calmejane I'm Just curious: what's your merge policy? I saw you haven't merged any PR on this repo using GitHub provided tools. Why that?

I'm using a private copy of this repository for implementing and testing features are are under NDA. I'm often far advanced from the public master or dev branches.
Until now, I always had conflicts and was unable to directly include new code through gitHub automatic merge tool. I manually add a remote to contributors and either cherry-pick or rebase their code into my most advanced branches (and sometimes have to amend commits due to clang-format not being run :) ).

**Comment by romansavrulin** [comment]
@christophe-calmejane I see, thank you. I'm not pushing you, just asking because I was planning to propose some minor improvements to certain parts of the library and need to know what the release cycle is.

**Comment by christophe-calmejane** [comment]
I integrated your fix for this PR into my private copy, it will show up in the coming days/weeks in the public repository. I squashed all your 3 commits into a single one for clarity. Remember that contributors only appear once the master branch include your commits but expect a new minor version soon anyway as I want to push my C/lua bindings publicly

**Pull request closed without merging**
